// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artback/mvp/pkg/vending (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	products "github.com/artback/mvp/pkg/products"
	vending "github.com/artback/mvp/pkg/vending"
	gomock "github.com/golang/mock/gomock"
)

// VendingRepsitory is a mock of Repository interface.
type VendingRepsitory struct {
	ctrl     *gomock.Controller
	recorder *VendingRepsitoryMockRecorder
}

// VendingRepsitoryMockRecorder is the mock recorder for VendingRepsitory.
type VendingRepsitoryMockRecorder struct {
	mock *VendingRepsitory
}

// NewVendingRepsitory creates a new mock instance.
func NewVendingRepsitory(ctrl *gomock.Controller) *VendingRepsitory {
	mock := &VendingRepsitory{ctrl: ctrl}
	mock.recorder = &VendingRepsitoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VendingRepsitory) EXPECT() *VendingRepsitoryMockRecorder {
	return m.recorder
}

// BuyProduct mocks base method.
func (m *VendingRepsitory) BuyProduct(arg0 context.Context, arg1 string, arg2 products.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyProduct", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuyProduct indicates an expected call of BuyProduct.
func (mr *VendingRepsitoryMockRecorder) BuyProduct(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyProduct", reflect.TypeOf((*VendingRepsitory)(nil).BuyProduct), arg0, arg1, arg2)
}

// GetAccount mocks base method.
func (m *VendingRepsitory) GetAccount(arg0 context.Context, arg1 string) (*vending.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(*vending.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *VendingRepsitoryMockRecorder) GetAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*VendingRepsitory)(nil).GetAccount), arg0, arg1)
}

// IncrementDeposit mocks base method.
func (m *VendingRepsitory) IncrementDeposit(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDeposit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDeposit indicates an expected call of IncrementDeposit.
func (mr *VendingRepsitoryMockRecorder) IncrementDeposit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDeposit", reflect.TypeOf((*VendingRepsitory)(nil).IncrementDeposit), arg0, arg1, arg2)
}

// SetDeposit mocks base method.
func (m *VendingRepsitory) SetDeposit(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeposit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDeposit indicates an expected call of SetDeposit.
func (mr *VendingRepsitoryMockRecorder) SetDeposit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeposit", reflect.TypeOf((*VendingRepsitory)(nil).SetDeposit), arg0, arg1, arg2)
}
