name: Makefile CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  
   testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: unit test
      run: make test
      
    - name: integration tests
      run: make test-integration   

