name: Makefile CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
   test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: unit
      run: make test
      
    - name: integration
      run: make test-integration   

